'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports System.Data.Entity.Core.Objects
Imports System.Linq

Partial Public Class FSVEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=FSVEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub


    Public Overridable Function GetCustomerIDByContactName(contactName As String) As ObjectResult(Of GetCustomerIDByContactName_Result)
        Dim contactNameParameter As ObjectParameter = If(contactName IsNot Nothing, New ObjectParameter("ContactName", contactName), New ObjectParameter("ContactName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetCustomerIDByContactName_Result)("GetCustomerIDByContactName", contactNameParameter)
    End Function

    Public Overridable Function GetEmployeeIDByLastName(lastName As String) As ObjectResult(Of GetEmployeeIDByLastName_Result)
        Dim lastNameParameter As ObjectParameter = If(lastName IsNot Nothing, New ObjectParameter("LastName", lastName), New ObjectParameter("LastName", GetType(String)))

        Return DirectCast(Me, IObjectContextAdapter).ObjectContext.ExecuteFunction(Of GetEmployeeIDByLastName_Result)("GetEmployeeIDByLastName", lastNameParameter)
    End Function

End Class
